#!/bin/bash
set -e;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Create user and database for n8n
    CREATE USER $N8N_PGSQL_USER WITH PASSWORD '$N8N_PGSQL_PASSWORD';
    CREATE DATABASE $N8N_PGSQL_DB;
    GRANT ALL PRIVILEGES ON DATABASE $N8N_PGSQL_DB TO $N8N_PGSQL_USER;

    -- Create user and database for Metabase
    CREATE USER $METABASE_PGSQL_USER WITH PASSWORD '$METABASE_PGSQL_PASSWORD';
    CREATE DATABASE $METABASE_PGSQL_DB;
    GRANT ALL PRIVILEGES ON DATABASE $METABASE_PGSQL_DB TO $METABASE_PGSQL_USER;

    -- Grant privileges on the public schema for n8n
    \c $N8N_PGSQL_DB
    GRANT USAGE ON SCHEMA public TO $N8N_PGSQL_USER;
    GRANT CREATE ON SCHEMA public TO $N8N_PGSQL_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $N8N_PGSQL_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $N8N_PGSQL_USER;

    -- Grant privileges on the public schema for Metabase
    \c $METABASE_PGSQL_DB
    GRANT USAGE ON SCHEMA public TO $METABASE_PGSQL_USER;
    GRANT CREATE ON SCHEMA public TO $METABASE_PGSQL_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $METABASE_PGSQL_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $METABASE_PGSQL_USER;

	-- Setup AI vectors support
	\c $POSTGRES_DB
	create extension if not exists pgvector;
	create extension if not exists vectorscale;
EOSQL